### ISSUE TITLE
Error while loading external data into the alignment GUI

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblapps#112]
Hi! I'm trying to launch the GUI on my own data which I've transformed into ALF files but am running into an error while loading the data into the GUI.

```
Traceback (most recent call last):
  File "C:\Users\guido\Repositories\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 1276, in data_button_pressed
    self.plotdata = pd.PlotData(self.probe_path, data,
  File "c:\users\guido\repositories\iblapps\atlaselectrophysiology\plot_data.py", line 63, in __init__
    shank_spikes = np.isin(self.chn_ind_all[self.data['clusters'].channels[self.data['spikes'].clusters]],
IndexError: index 331 is out of bounds for axis 0 with size 325
```

I've tried to see what's going wrong but I can't figure it out. It looks as though `clusters.channels` is indexed by `spikes.clusters` which is causing problems. I also don't see how this `np.isin` is going to result into something that can index `spikes` on line 68.

Any help would be greatly appreciated!

**Comment by guidomeijer** [comment]
My mistake, I just inputted the wrong data folder. All working now.
