### ISSUE TITLE
Catch error when spike sorting doesn't exist

### ISSUE THREAD

**Issue by cskrasniak** [int-brain-lab/iblapps#16]
Currently when trying to load a session for which spike sorting doesn't exist, the gui crashes and closes. It would save a lot of time if instead you could catch this error and maybe display that spikes don't exist for this session on the gui.

example error when loading session without spike sorting: ```python ephys_atlas_gui.py
objc[23859]: Class RunLoopModeTracker is implemented in both /Users/ckrasnia/opt/anaconda3/envs/iblenv/lib/libQt5Core.5.9.7.dylib (0x108befa80) and /Users/ckrasnia/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/cv2/.dylibs/QtCore (0x1a2cd027f0). One of the two will be used. Which one is undefined.
Connected to https://alyx.internationalbrainlab.org as chrisk
Connecting cskrasniak@datajoint.internationalbrainlab.org:3306
CSH_ZAD_021
probe01
2020-06-15
2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset spikes.depths not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset spikes.amps not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset spikes.times not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset spikes.clusters not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset channels.localCoordinates not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset channels.rawInd not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset clusters.metrics not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset clusters.peakToTrough not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.81 WARNING  [one.py:178] dataset clusters.waveforms not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.82 WARNING  [one.py:178] dataset clusters.channels not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
2020-11-03 13:54:54.82 WARNING  [one.py:178] dataset _iblqc_ephysSpectralDensity.amps not found for session: 2595d3eb-1c32-4688-be85-c25d3434561b
Traceback (most recent call last):
  File "ephys_atlas_gui.py", line 876, in data_button_pressed
    alf_path, ephys_path, self.chn_depths, self.sess_notes = self.loaddata.get_data()
  File "/Users/ckrasnia/Desktop/Zador_Lab/IBL/int-brain-lab/iblapps/atlaselectrophysiology/load_data.py", line 226, in get_data
    self.chn_coords = np.load(Path(alf_path, 'channels.localCoordinates.npy'))
  File "/Users/ckrasnia/opt/anaconda3/envs/iblenv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ckrasnia/Desktop/Zador_lab/IBL/FlatironData/zadorlab/Subjects/CSH_ZAD_021/2020-06-15/001/alf/probe01/channels.localCoordinates.npy'
Abort trap: 6
```

**Comment by mayofaulkner** [comment]
Okay, yeah thanks for the suggestion! I will incorporate that into the next release
