### ISSUE TITLE
ModuleNotFoundError: No module named 'spikeglx'

### ISSUE THREAD

**Issue by GuilleSGCUPO** [int-brain-lab/iblapps#62]
Hiii, I have been using the anaconda prompt and gui for histological alignment of Neuropixels 1.0 probes in brain slices. However, I am having troubles to open the gui, I keep receiving the same error as shown in the code below. However, months ago, during the UCL-Neuropixels course, I was able to open it for using the atlas electrophysiology tool. Anybody knows how may I fix it?
Thank you on behalf

```
(phy2) C:\Users\Analisis\Desktop\S1-Mag NP\SI-Mag-NP#1_g0\SI-Mag-NP#1_g0_ap>conda activate iblenv

(iblenv) C:\Users\Analisis\Desktop\S1-Mag NP\SI-Mag-NP#1_g0\SI-Mag-NP#1_g0_ap>cd C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab

(iblenv) C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab>cd C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology

(iblenv) C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology>python ephys_atlas_gui.py -o True
Traceback (most recent call last):
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 13, in <module>
    from atlaselectrophysiology.load_data import LoadData
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology\load_data.py", line 4, in <module>
    import ibllib.pipes.histology as histology
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\ibllib-repo\ibllib\pipes\__init__.py", line 5, in <module>
    from ibllib.io.flags import FLAG_FILE_NAMES
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\ibllib-repo\ibllib\io\__init__.py", line 1, in <module>
    import spikeglx
ModuleNotFoundError: No module named 'spikeglx'
```

**Comment by mayofaulkner** [comment]
Hi please could you do `pip install ibl-neuropixel`

**Comment by GuilleSGCUPO** [comment]
Thank you so much, that error is solved. However, I'm facing a new one that I show in the code below. I am wondering, has there been an update of the github files or code that maybe I have not renewed yet?
Thanks again :)

```
(iblenv) C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology>python ephys_atlas_gui.py -o True
Traceback (most recent call last):
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 13, in <module>
    from atlaselectrophysiology.load_data import LoadData
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\iblapps\atlaselectrophysiology\load_data.py", line 4, in <module>
    import ibllib.pipes.histology as histology
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\ibllib-repo\ibllib\pipes\histology.py", line 10, in <module>
    import ibllib.atlas as atlas
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\ibllib-repo\ibllib\atlas\__init__.py", line 1, in <module>
    from .atlas import *  # noqa
  File "C:\Users\Analisis\Desktop\Scripts KilosortMATLAB\Histological Alignment\int-brain-lab\ibllib-repo\ibllib\atlas\atlas.py", line 8, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**Comment by mayofaulkner** [comment]
Ahh, can you also do `pip install boto3`

**Comment by mayofaulkner** [comment]
The channel mapping comes from what is in the channels.localCoordinates.npy file. Depending on the channel map that you used for spikesorting is should reflect the correct channel map. Does it not in your case?
