### ISSUE TITLE
error during preparing Kilosort v3.0 data

### ISSUE THREAD

**Issue by chongtianyifa** [int-brain-lab/iblapps#69]
Hi IBL teams,
I failed to preapare GUI data using kilosort3.0 data.
I used peter's code in #40 . The extract_files.py file was modifed as in #65 . In addition, I modified alf.py and model.py as in #36 (I did not use the develop branch) as the data was merged by phy. My raw data and kilosort data was put in the same folder. During converting the data (after running for several minutes), I got these errors:

Converting to ALF:  44%|████▍     | 55/125 [00:49<01:11,  1.02s/it]
Extracting waveforms:   0%|          | 0/903.3431333333333 [00:00<?, ?it/s]
Extracting waveforms: 100%|██████████| 903.3431333333333/903.3431333333333 [03:51<00:00,  3.90it/s]
Converting to ALF: 145it [04:59,  2.07s/it]
2022-09-05 23:26:46.888 INFO     [extract_files.py:82] Computing QC for D:\Lei\data\single unit\Neuropixel\Lei-depth 3.8_g0\Lei-depth 3.8_g0_imec0\Lei-depth 3.8_g0_t0.imec0.ap.bin
104it [14:21,  8.28s/it]
2022-09-05 23:41:09.489 INFO     [extract_files.py:82] Computing QC for D:\Lei\data\single unit\Neuropixel\Lei-depth 3.8_g0\Lei-depth 3.8_g0_imec0\Lei-depth 3.8_g0_t0.imec0.lf.bin
  0%|          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\windows\_windows.py", line 2214, in get_window
    beta = float(window)
ValueError: could not convert string to float: 'hanning'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\windows\_windows.py", line 2232, in get_window
    winfunc = _win_equiv[winstr]
KeyError: 'hanning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Lei\code\python\PrepareIblappsData.py", line 24, in <module>
    extract_rmsmap(lf_bin_path, out_folder=out_path)
  File "c:\users\chenlab\iblapps\atlaselectrophysiology\extract_files.py", line 93, in extract_rmsmap
    rms = rmsmap(fbin, spectra=spectra)
  File "c:\users\chenlab\iblapps\atlaselectrophysiology\extract_files.py", line 58, in rmsmap
    _, w = signal.welch(
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\_spectral_py.py", line 446, in welch
    freqs, Pxx = csd(x, x, fs=fs, window=window, nperseg=nperseg,
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\_spectral_py.py", line 580, in csd
    freqs, _, Pxy = _spectral_helper(x, y, fs, window, nperseg, noverlap, nfft,
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\_spectral_py.py", line 1780, in _spectral_helper
    win, nperseg = _triage_segments(window, nperseg, input_length=x.shape[-1])
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\_spectral_py.py", line 2003, in _triage_segments
    win = get_window(window, nperseg)
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\scipy\signal\windows\_windows.py", line 2234, in get_window
    raise ValueError("Unknown window type.") from e
ValueError: Unknown window type.

Can you give me some tips about these issues?

Thanks,
Lei

**Comment by chongtianyifa** [comment]
As an update, I just tried converting data that Phy does not curate. However, I ended up with the exact same error as above.

**Comment by mayofaulkner** [comment]
Hi, it looks like there was a change in the recent scipy. If you pull the latest changes from iblapps master or develop this has been updated. You might need to also update to the latest ONE, this can be done using 
```
pip install ONE-api --upgrade
```

One thing to note is that to convert to alf after curating in phy you will still need to use the develop branch of phylib. 

Let me know if that helps and if you need any further help.

Thanks,
Mayo

**Comment by chongtianyifa** [comment]
Hi Mayo,

Thanks for the help.
First, is it correct to install a branch by
`pip uninstall phylib`
`pip install git+https://github.com/cortex-lab/phylib.git@alf_conversion_merge`?

I just pulled the latest master or develop branch and updated to the latest ONE. I tested data without curating. 
When I used the phylib master, I got errors very quickly:
Traceback (most recent call last):
  File "D:\Lei\code\python\PrepareIblappsData.py", line 32, in <module>
    m = ephysqc.phy_model_from_ks2_path(ks_path, ephys_path, ap_bin_path)
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\ibllib\ephys\ephysqc.py", line 435, in phy_model_from_ks2_path
    m = model.TemplateModel(dir_path=ks2_path,
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\model.py", line 339, in __init__
    self._load_data()
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\model.py", line 437, in _load_data
    self.traces = self._load_traces(self.channel_mapping)
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\model.py", line 568, in _load_traces
    traces = get_ephys_reader(
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\traces.py", line 498, in get_ephys_reader
    return klass(arg, **kwargs)
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\traces.py", line 317, in __init__
    self._mmaps = [
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\traces.py", line 318, in <listcomp>
    _memmap_flat(path, dtype=dtype, n_channels=n_channels, offset=offset, mode=mode)
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\traces.py", line 161, in _memmap_flat
    assert (fsize - offset) % (item_size * n_channels) == 0,\
AssertionError: Inconsistent number of channels between the params file and the binary dat file

Then I used the phylib alf_conversion_merge branch, I got errors:
Converting to ALF:  44%|████▍     | 55/125 [00:42<00:54,  1.29it/s]
Traceback (most recent call last):
  File "D:\Lei\code\python\PrepareIblappsData.py", line 34, in <module>
    ac.convert(out_path, force=True, ampfactor=_sample2v(ap_bin_path))
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\alf.py", line 130, in convert
    self.model.save_spikes_subset_waveforms(
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\model.py", line 1385, in save_spikes_subset_waveforms
    export_waveforms(
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\traces.py", line 655, in export_waveforms
    writer = NpyWriter(path, shape, dtype)
  File "C:\Users\ChenLab\anaconda3\envs\iblenv\lib\site-packages\phylib\io\traces.py", line 556, in __init__
    self.fp = open(path, 'wb')
OSError: [Errno 22] Invalid argument: 'D:\\Lei\\data\\single unit\\Neuropixel\\Lei-depth 3.8_g0\\noCurating\\_phy_spikes_subset.waveforms.npy'

Please let me know what else I should change.

Thanks,
Lei

**Comment by chongtianyifa** [comment]
Hi Mayo,

I think the issue might be that my pathname is too long. I changed the location of _phy_spikes_subset.waveforms.npy and manually redirected it in line 556 of traces.py. Then it worked. Do you have any way to improve this?

Thanks,
Lei

**Comment by mayofaulkner** [comment]
Hi, just to let you know that this error has been fixed on the latest version of phylib (v.2.4.3). This also has the alf conversion implemented and can be used as the default. Please switch to the main install of phylib
```
pip uninstall phylib
pip install phylib
```
