### ISSUE TITLE
Cannot open the GUI

### ISSUE THREAD

**Issue by Virginia9733** [int-brain-lab/iblapps#74]
Hit there, thanks for developing this wonderful tool!

When I try to launch the GUI as an external user, I encountered this error message:

conda activate iblenv
path to the ephys_atlas_gui.py file on your computer
python int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py -o True 

Traceback (most recent call last):
  File "D:\repos\International-Brain-Labratory\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 2164, in <module>
    mainapp = MainWindow(offline=args.offline, probe_id=args.insertion, remote=args.remote)
  File "D:\repos\International-Brain-Labratory\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 66, in __init__
    self.loaddata = LoadDataLocal()
  File "d:\repos\international-brain-labratory\iblapps\atlaselectrophysiology\load_data_local.py", line 18, in __init__
    ONE(silent=True, password='international')
  File "C:\Users\muhang\miniconda3\envs\iblenv\lib\site-packages\one\api.py", line 1360, in ONE
    return OneAlyx(mode=mode, wildcards=wildcards, **kwargs)
  File "C:\Users\muhang\miniconda3\envs\iblenv\lib\site-packages\one\api.py", line 1401, in __init__
    self._web_client = wc.AlyxClient(username=username,
  File "C:\Users\muhang\miniconda3\envs\iblenv\lib\site-packages\one\webclient.py", line 500, in __init__
    self._par = one.params.get(client=base_url, silent=self.silent, username=username)
  File "C:\Users\muhang\miniconda3\envs\iblenv\lib\site-packages\one\params.py", line 218, in get
    cache = cache_map.CLIENT_MAP[client_key or cache_map.DEFAULT]
AttributeError: 'IBLParams' object has no attribute 'DEFAULT'

**Comment by Virginia9733** [comment]
I started over again, but still encountered the error
![Uploading Screenshot 2022-11-14 144909.png…]()

**Comment by mayofaulkner** [comment]
Hello, could you please navigate to `C:\Users\muhang\AppData\Roaming` and delete the folder that is called `.one` and try again.

Let me know if that works!

**Comment by Virginia9733** [comment]
Now it works! Thanks!

**Comment by jonahpearl** [comment]
Hi there — I'm encountering the same error but on a Mac. I don't see any Roaming folder under `/Users/jonahpearl/Library/ApplicationSupport/` or `/Library/Application\ Support/`, can you suggest another place to look?

**Comment by jonahpearl** [comment]
Nvm I found it in ~/.one. (From [here](https://github.com/int-brain-lab/iblutil/blob/08c10290fb488999b6ebe0c0331650e4a0f22ab3/iblutil/io/params.py#L44)). I ran `rm -rf ~/.one` and that fixed it :)
